set -g status-style "bg=black,fg=white"

set -g status-left "#[bold]#[fg=cyan]#S #[fg=white]"
set -g status-right "#[fg=yellow]%Y-%m-%d #[fg=cyan]%H:%M"

# Window list style
setw -g window-status-format " #[fg=brightblack]#W "
setw -g window-status-current-format " #[bold]#[fg=green]#W#[fg=white] "

set -g status-justify absolute-centre

# Change prefix key from Ctrl-b to Ctrl-s
unbind C-b
set-option -g prefix C-s
bind C-s send-prefix

bind-key -r i run-shell "tmux neww btop"
bind-key -r p run-shell "tmux neww pulsemixer"
bind-key -r t run-shell "tmux neww tenki"

set -g mouse on

# Start from index 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*:Tc"
